keys:
  - &leona EB5CEED62922C6050F9FC85BD5B08ADFC75E3605
  - &bij age14s6jax4hc2uz6rusud4lna0uc9m28u9yurv2ewwjchnr2cjqa43qqw2xqp
  - &dwd age1xph9c9rtyjrz3cnd6t940dnzuruqw27l7yp98ac33rdz53q429gsu702k4
  - &enari age1qvevvg59t6y82jpyg2wqvgekj648dwgzz8hwuu73srv68ulykqwqcl9zxg
  - &gaika age19yum7ka8gn7pm5qgrjhcx4ac2sclk3d7wl2088750v508ghzrpnsjwvynj
  - &haku age1r0ry9fmygcw0w7ltwkff7wlcm0g57g0lu62m92yz6e73kmrha9ps3xvdw6
  - &kupe age1udlqpz3mcwnnrng4wg7w79674e4plrydmeqna3axy8sczq5gushqdhac3p
  - &ladon age1ccn87qg8fe9jd2ct96j9qcmsfmp2y8hpmenmn3tdm8k9zvtvx9ysl0hklt
  - &laurel age1p2f0el5z3jn2gt70w249fvkzewcqytwx9vez4skd598v7d7dtpxq86enup
  - &thia age1st8tawt7qsf7q24nknscrwzw6d6fcveylggtf2az36j0nke7jv7sx7ce4q
  - &turingmachine age1rcxgtdwh3u7u6lzh9558sqfrs9ndwnzhsjqj57hvdtapcjynvs8szhdw4t
  - &sphere age17ldwzf52ked9wpqhrw55mhc6ax5r6eh0jpefx6lqql8w5zhlsp4q4g64zr
creation_rules:
  - path_regex: secrets/all/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *leona
        age:
          - *bij
          - *dwd
          - *enari
          - *gaika
          - *haku
          - *kupe
          - *ladon
          - *laurel
          - *thia
          - *turingmachine
          - *sphere

  # hosts
  - path_regex: secrets/hosts/bij.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *bij
  - path_regex: secrets/hosts/dwd.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *dwd
  - path_regex: secrets/hosts/enari.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
  - path_regex: secrets/hosts/gaika.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *gaika
  - path_regex: secrets/hosts/haku.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *haku
  - path_regex: secrets/hosts/kupe.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/hosts/ladon.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *ladon
  - path_regex: secrets/hosts/laurel.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *laurel
  - path_regex: secrets/hosts/thia.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia
  - path_regex: secrets/hosts/turingmachine.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *turingmachine
  - path_regex: secrets/hosts/sphere.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *sphere

  # profiles
  - path_regex: secrets/profiles/desktop.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia
          - *turingmachine

  # services
  - path_regex: secrets/services/(gitea|matrix-old).yaml
    key_groups:
      - pgp:
          - *leona
  - path_regex: secrets/services/(hedgedoc|matrix|netbox|pleroma|vikunja|vaultwarden).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *laurel
  - path_regex: secrets/services/(firefly-iii|grocy|ical-merger|snipe-it).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *bij
  - path_regex: secrets/services/(keycloak-old|hydra-sso).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *ladon
  - path_regex: secrets/services/mail.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/services/(monitoring|plausible).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
  - path_regex: secrets/services/dns-knot-secondary.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
          - *bij
  - path_regex: secrets/services/(keycloak|ldap).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *sphere
  - path_regex: secrets/services/(int-acme-ca|nextcloud|paperless|bn-smarthome).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia