keys:
  - &leona B50CB5BA6A620411098CD9C8F0E55407FC6FF7BA
  - &arche age1qly0tm983m4cssmvt4fcgekrezez86lclpmwu3aezk6jyyhxte0q3l3vad
  - &bij age14s6jax4hc2uz6rusud4lna0uc9m28u9yurv2ewwjchnr2cjqa43qqw2xqp
  - &ceto age1j87zqrvqvku98rex3w2uw7gr57wgvyzfghq7g6v076ee5pa02qtqju0yq0
  - &dwd age1xph9c9rtyjrz3cnd6t940dnzuruqw27l7yp98ac33rdz53q429gsu702k4
  - &enari age108r86j5zcd9uz22k9f73dh5pfgst8xqv7ffj7xwgspad6zk4xu0qtcngte
  - &freyda age1extnp5hlhrzraj96n3ntqhlr7p6jxcypwxf4a20vtjf6gc0ch4tq5qdljp
  - &gaika age19yum7ka8gn7pm5qgrjhcx4ac2sclk3d7wl2088750v508ghzrpnsjwvynj
  - &kupe age1udlqpz3mcwnnrng4wg7w79674e4plrydmeqna3axy8sczq5gushqdhac3p
  - &laurel age1p2f0el5z3jn2gt70w249fvkzewcqytwx9vez4skd598v7d7dtpxq86enup
  - &naya age1x7425df963ql0a5d5lpv242e3cm9cna5zxp0vs4gwugdmmsmm57sawvnr6
  - &rutile age1tfsxwt56ww42tzuxv65fmpx0eefa8qrek2wrn2wtxdaqpddugsnqg06p8m
  - &thia age1st8tawt7qsf7q24nknscrwzw6d6fcveylggtf2az36j0nke7jv7sx7ce4q
  - &turingmachine age1rcxgtdwh3u7u6lzh9558sqfrs9ndwnzhsjqj57hvdtapcjynvs8szhdw4t
  - &sphere age17ldwzf52ked9wpqhrw55mhc6ax5r6eh0jpefx6lqql8w5zhlsp4q4g64zr
creation_rules:
  - path_regex: secrets/all/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *leona
        age:
          - *arche
          - *bij
          - *ceto
          - *dwd
          - *enari
          - *freyda
          - *gaika
          - *kupe
          - *laurel
          - *naya
          - *rutile
          - *thia
          - *turingmachine
          - *sphere

  # hosts
  - path_regex: secrets/hosts/arche.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *bij
  - path_regex: secrets/hosts/bij.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *bij
  - path_regex: secrets/hosts/ceto.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *ceto
  - path_regex: secrets/hosts/dwd.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *dwd
  - path_regex: secrets/hosts/enari.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
  - path_regex: secrets/hosts/freyda.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *freyda
  - path_regex: secrets/hosts/gaika.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *gaika
  - path_regex: secrets/hosts/kupe.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/hosts/laurel.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *laurel
  - path_regex: secrets/hosts/naya.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *naya
  - path_regex: secrets/hosts/rutile.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *rutile
  - path_regex: secrets/hosts/thia.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia
  - path_regex: secrets/hosts/turingmachine.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *turingmachine
  - path_regex: secrets/hosts/sphere.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *sphere

  # profiles
  - path_regex: secrets/profiles/desktop.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *ceto
          - *freyda
          - *thia
          - *turingmachine

  # services
  - path_regex: secrets/services/(gitea|matrix-old).yaml
    key_groups:
      - pgp:
          - *leona
  - path_regex: secrets/services/(hedgedoc|matrix|netbox|outline|tandoor|pleroma|vikunja|vaultwarden).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *laurel
  - path_regex: secrets/services/(firefly-iii|grocy|ical-merger|snipe-it).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *bij
  - path_regex: secrets/services/mail.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/services/(gitlab|gitlab-runner).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
  - path_regex: secrets/services/(monitoring|plausible).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *rutile
  - path_regex: secrets/services/dns-knot-primary.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/services/dns-knot-secondary.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
          - *bij
  - path_regex: secrets/services/(keycloak|ldap).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *sphere
  - path_regex: secrets/services/(actual-budget|int-acme-ca|nextcloud|paperless|bn-smarthome).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia
  - path_regex: secrets/services/stag-keycloak.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *naya
