keys:
  - &leona B50CB5BA6A620411098CD9C8F0E55407FC6FF7BA
  - &arche age1qly0tm983m4cssmvt4fcgekrezez86lclpmwu3aezk6jyyhxte0q3l3vad
  - &biro age1f79kpv0ef9p7skmwtc3sd3wa4c93efr5yq8e6nlq4nfxvzvc943swuzxa0
  - &ceto age1j87zqrvqvku98rex3w2uw7gr57wgvyzfghq7g6v076ee5pa02qtqju0yq0
  - &dwd age1xph9c9rtyjrz3cnd6t940dnzuruqw27l7yp98ac33rdz53q429gsu702k4
  - &enari age108r86j5zcd9uz22k9f73dh5pfgst8xqv7ffj7xwgspad6zk4xu0qtcngte
  - &freyda age1extnp5hlhrzraj96n3ntqhlr7p6jxcypwxf4a20vtjf6gc0ch4tq5qdljp
  - &gaika age19yum7ka8gn7pm5qgrjhcx4ac2sclk3d7wl2088750v508ghzrpnsjwvynj
  - &kupe age1udlqpz3mcwnnrng4wg7w79674e4plrydmeqna3axy8sczq5gushqdhac3p
  - &laurake age17h9eyjh575jte8tz45rwkrc5ksd4gyfn6lt75lzrx4emx3vmvqysqq9h2j
  - &moka age1r8dpxty0r2ty86r6gj7df2ejfd8x7pj75tnyulplud3dcevj5acqa88z4y
  - &neris age19d5w6qtgvwvy0djaye085ae4qk9vmmj95fwqsn8a89mxz3zfkcsqg5zlnc
  - &rutile age1tfsxwt56ww42tzuxv65fmpx0eefa8qrek2wrn2wtxdaqpddugsnqg06p8m
  - &thia age1st8tawt7qsf7q24nknscrwzw6d6fcveylggtf2az36j0nke7jv7sx7ce4q
  - &turingmachine age1rcxgtdwh3u7u6lzh9558sqfrs9ndwnzhsjqj57hvdtapcjynvs8szhdw4t
  - &shioto age1cdcgwcgls6aj0lju7w6fm97ewzg7jy86ndk2ygmygad8takns56qu8cvwc
creation_rules:
  - path_regex: secrets/all/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *leona
        age:
          - *arche
          - *biro
          - *ceto
          - *dwd
          - *enari
          - *freyda
          - *gaika
          - *kupe
          - *laurake
          - *moka
          - *neris
          - *rutile
          - *thia
          - *turingmachine
          - *shioto

  # hosts
  - path_regex: secrets/hosts/arche.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *arche
  - path_regex: secrets/hosts/biro.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *biro
  - path_regex: secrets/hosts/ceto.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *ceto
  - path_regex: secrets/hosts/dwd.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *dwd
  - path_regex: secrets/hosts/enari.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
  - path_regex: secrets/hosts/freyda.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *freyda
  - path_regex: secrets/hosts/gaika.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *gaika
  - path_regex: secrets/hosts/kupe.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/hosts/laurake.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *laurake
  - path_regex: secrets/hosts/moka.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *moka
  - path_regex: secrets/hosts/neris.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *neris
  - path_regex: secrets/hosts/rutile.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *rutile
  - path_regex: secrets/hosts/thia.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia
  - path_regex: secrets/hosts/turingmachine.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *turingmachine
  - path_regex: secrets/hosts/shioto.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *shioto

  # profiles
  - path_regex: secrets/profiles/desktop.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *ceto
          - *freyda
          - *thia
          - *turingmachine

  # services
  - path_regex: secrets/services/(gitea|matrix-old).yaml
    key_groups:
      - pgp:
          - *leona
  - path_regex: secrets/services/(hedgedoc|matrix|netbox|outline|tandoor|vikunja|vaultwarden).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *laurake
  - path_regex: secrets/services/(firefly-iii|snipe-it).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *biro
  - path_regex: secrets/services/mail.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/services/(gitlab|gitlab-runner).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
  - path_regex: secrets/services/(monitoring|plausible).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *rutile
  - path_regex: secrets/services/dns-knot-primary.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *kupe
  - path_regex: secrets/services/dns-knot-secondary.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *enari
          - *biro
  - path_regex: secrets/services/(keycloak|ldap).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *shioto
  - path_regex: secrets/services/(actual-budget|int-acme-ca|nextcloud|paperless|bn-smarthome).yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *thia
  - path_regex: secrets/services/stag-keycloak.yaml
    key_groups:
      - pgp:
          - *leona
        age:
          - *neris
