{
 "title": "General System metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(system_uptime, host)"
    }
   },
   {
    "name": "temp_chip",
    "label": "temp chip",
    "query": {
     "query": "label_values(sensors_temp_input{host=\"$host\"}, chip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(net_bytes_recv{host=\"$host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "systemd failed units",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(systemd_units_active_code{host=\"$host\",active=\"failed\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Load (5min)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load5{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Load (15min)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load15{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$host\"}",
     "legendFormat": "Used Mem"
    }
   ]
  },
  {
   "title": "Root FS used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\", path=\"/\"}"
    }
   ]
  },
  {
   "title": "systemd running units",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(systemd_units_active_code{host=\"$host\",active=~\"active\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(net_bytes_sent{host=\"$host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed MD Raid Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mdstat_DisksFailed{host=\"$host\"}",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "CPU (total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_system{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_user{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "user"
    },
    {
     "expr": "sensors_temp_input{host=\"$host\", chip=~\"$temp_chip\"}",
     "legendFormat": "temp - {{chip}}"
    },
    {
     "expr": "sensors_temp_max{host=\"$host\", chip=~\"$temp_chip\"}",
     "legendFormat": "temp - high - {{chip}}"
    }
   ]
  },
  {
   "title": "CPU (per core)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_system{host=~\"$host\",cpu!=\"cpu-total\"} + cpu_usage_user{host=~\"$host\",cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    },
    { "legendFormat": "user-{{cpu}}" }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "system_load5{host=~\"$host\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "system_load15{host=~\"$host\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_used{host=\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mem_cached{host=~\"$host\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem_total{host=~\"$host\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=\"$host\"}[2m])",
     "legendFormat": "RX {{interface}}"
    },
    {
     "expr": "-rate(net_bytes_sent{host=\"$host\"}[2m])",
     "legendFormat": "TX {{interface}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\",device!~\"dm-[0-9]*\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "-rate(diskio_read_time{host=\"$host\"}[60s])",
     "legendFormat": "read - {{name}}"
    },
    {
     "expr": "rate(diskio_write_time{host=\"$host\"}[60s])",
     "legendFormat": "write - {{name}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-rate(diskio_read_bytes{host=\"$host\"}[1m])",
     "legendFormat": "read - {{name}}"
    },
    {
     "expr": "rate(diskio_write_bytes{host=\"$host\"}[1m])",
     "legendFormat": "write - {{name}}"
    }
   ]
  }
 ]
}