{
 "title": "Hosts Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Offline Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(up != 1) or vector(0)" }
   ]
  },
  {
   "title": "Failed systemd services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(systemd_units_active_code{active=\"failed\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "No. of nearly Full Disks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(disk_used_percent >= 85) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpu_usage_system + cpu_usage_user) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RAM ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mem_used_percent) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Main Disk  Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(disk_used_percent{path=\"/\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Offline hosts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "up != 1" }
   ]
  },
  {
   "title": "Failed systemd services",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "systemd_units_active_code{active=\"failed\"}"
    }
   ]
  },
  {
   "title": "Last successful BorgBackup",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - borgbackup_last_successful_archive"
    }
   ]
  }
 ]
}