{
 "title": "Knot Resolver DNS",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(kresd_worker_tls, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/Responses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(kresd_request_total{host=\"$host\"}[90s])",
     "legendFormat": "Requests Total"
    },
    {
     "expr": "increase(kresd_answer_total{host=\"$host\"}[90s])",
     "legendFormat": "Responses Total"
    }
   ]
  },
  {
   "title": "Answers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(kresd_answer_total{host=\"$host\"}[90s])",
     "legendFormat": "Answers Total"
    },
    {
     "expr": "increase(kresd_answer_rd{host=\"$host\"}[90s])",
     "legendFormat": "Recursion desired"
    },
    {
     "expr": "increase(kresd_answer_edns0{host=\"$host\"}[90s])",
     "legendFormat": "EDNS0 available"
    },
    {
     "expr": "increase(kresd_answer_do{host=\"$host\"}[90s])",
     "legendFormat": "DNSSEC OK"
    }
   ]
  },
  {
   "title": "Answers/Cached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "increase(kresd_answer_total{host=\"$host\"}[90s])",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(kresd_answer_cached{host=\"$host\"}[90s])",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(kresd_cache_read_leq{host=\"$host\"}[90s])",
     "legendFormat": "read  leq"
    },
    {
     "expr": "increase(kresd_cache_read_miss{host=\"$host\"}[90s])",
     "legendFormat": "read - miss"
    },
    {
     "expr": "increase(kresd_cache_write{host=\"$host\"}[90s])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "increase(kresd_latency_bucket{host=\"$host\", le!=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}