{
 "title": "Bind9",
 "tags": [ "service" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(bind_boot_time_seconds_gauge, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming Queries/s (myron)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total_counter{host=\"myron\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Queries/s (haku)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total_counter{host=\"haku\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Queries/s (naiad)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total_counter{host=\"naiad\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Named CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(bind_process_cpu_seconds_total_counter{host=\"$host\"}[120s])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bind_process_virtual_memory_bytes_gauge{host=\"$host\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "bind_process_resident_memory_bytes_gauge{host=\"$host\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Incoming Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total_counter{host=\"$host\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Request Opcodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_requests_total_counter{host=\"$host\",opcode!~\"RESERVED[0-9]*\"}[120s])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Response Results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_responses_total_counter{host=\"$host\"}[120s])",
     "legendFormat": "{{ result }}"
    }
   ]
  }
 ]
}