# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "zroot/vault/os/root";
    fsType = "zfs";
    options = [
      "zfsutil"
      "X-mount.mkdir"
    ];
  };

  fileSystems."/home" = {
    device = "zroot/vault/os/home";
    fsType = "zfs";
    options = [
      "zfsutil"
      "X-mount.mkdir"
    ];
  };

  fileSystems."/nix" = {
    device = "zroot/vault/os/nix";
    fsType = "zfs";
    options = [
      "zfsutil"
      "X-mount.mkdir"
    ];
  };

  fileSystems."/boot/disk0" = {
    device = "/dev/disk/by-uuid/F56E-D6F6";
    fsType = "vfat";
    options = [ "nofail" ];
  };

  fileSystems."/boot/disk1" = {
    device = "/dev/disk/by-uuid/F557-FBDF";
    fsType = "vfat";
    options = [ "nofail" ];
  };

  fileSystems."/boot/disk2" = {
    device = "/dev/disk/by-uuid/F53B-43F6";
    fsType = "vfat";
    options = [ "nofail" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
